name: Use Composite Action
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # REPLACE THE FOLLOWING WITH THE PROPER VALUES
      # - YOUR_GITHUB_USER_NAME
      # - YOUR_COMPOSITE_ACTION_REPO_NAME
      - uses: YOUR_GITHUB_USER_NAME/YOUR_COMPOSITE_ACTION_REPO_NAME@main
        with:
          PYTHON_VERSION: 3.8
